# Generated by Django 4.1.4 on 2022-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='something', max_length=55),
            preserve_default=False,
        ),
    ]
